export const dashboardMock = {
  project: {
    id: "project-1",
    key: "SP",
    name: "SprintPlanner Core",
    description: "Turning ideas into executable 4-week ventures.",
    status: "active",
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  kpis: {
    totalTasks: 42,
    openTasks: 27,
    overdueTasks: 5,
    blockedTasks: 3,
    dueThisWeek: 9,
    myOpenTasks: 11,
  },
  charts: {
    sprintRadar: {
      velocity: 76,
      executionConfidence: 82,
      riskLevel: 64,
      documentationQuality: 58,
      stakeholderEngagement: 71,
      focusScore: 69,
    },
    statusDistribution: [
      { status: "backlog", count: 10 },
      { status: "todo", count: 12 },
      { status: "in_progress", count: 9 },
      { status: "done", count: 8 },
      { status: "cancelled", count: 3 },
    ],
    priorityDistribution: [
      { priority: "High", count: 9 },
      { priority: "Medium", count: 21 },
      { priority: "Low", count: 12 },
    ],
    executionHeatmap: [
      { date: "2025-11-01", createdCount: 2, completedCount: 1 },
      { date: "2025-11-02", createdCount: 4, completedCount: 3 },
      { date: "2025-11-03", createdCount: 1, completedCount: 0 },
      { date: "2025-11-04", createdCount: 3, completedCount: 2 },
      { date: "2025-11-05", createdCount: 2, completedCount: 4 },
      { date: "2025-11-06", createdCount: 0, completedCount: 1 },
      { date: "2025-11-07", createdCount: 1, completedCount: 2 },
      { date: "2025-11-08", createdCount: 3, completedCount: 1 },
      { date: "2025-11-09", createdCount: 2, completedCount: 3 },
      { date: "2025-11-10", createdCount: 4, completedCount: 2 },
      { date: "2025-11-11", createdCount: 1, completedCount: 0 },
      { date: "2025-11-12", createdCount: 2, completedCount: 3 },
      { date: "2025-11-13", createdCount: 3, completedCount: 2 },
      { date: "2025-11-14", createdCount: 1, completedCount: 1 },
      { date: "2025-11-15", createdCount: 2, completedCount: 4 },
      { date: "2025-11-16", createdCount: 0, completedCount: 2 },
      { date: "2025-11-17", createdCount: 3, completedCount: 1 },
      { date: "2025-11-18", createdCount: 2, completedCount: 3 },
      { date: "2025-11-19", createdCount: 4, completedCount: 2 },
      { date: "2025-11-20", createdCount: 1, completedCount: 0 },
      { date: "2025-11-21", createdCount: 2, completedCount: 3 },
      { date: "2025-11-22", createdCount: 3, completedCount: 2 },
      { date: "2025-11-23", createdCount: 1, completedCount: 1 },
      { date: "2025-11-24", createdCount: 2, completedCount: 4 },
      { date: "2025-11-25", createdCount: 0, completedCount: 2 },
      { date: "2025-11-26", createdCount: 3, completedCount: 1 },
      { date: "2025-11-27", createdCount: 2, completedCount: 3 },
      { date: "2025-11-28", createdCount: 4, completedCount: 2 },
    ],
    goalVsActual: {
      label: "This Week",
      planned: 18,
      completed: 13,
    },
    riskBubbles: [
      {
        taskId: "t-1",
        key: "SP-12",
        title: "Ship dashboard MVP",
        daysUntilDue: -1,
        priorityScore: 3,
        status: "in_progress",
      },
      {
        taskId: "t-2",
        key: "SP-19",
        title: "Investor narrative draft",
        daysUntilDue: 2,
        priorityScore: 3,
        status: "todo",
      },
      {
        taskId: "t-3",
        key: "SP-21",
        title: "User interview notes",
        daysUntilDue: 5,
        priorityScore: 2,
        status: "todo",
      },
    ],
  },
  lists: {
    upcomingDeadlines: [
      {
        id: "t-1",
        key: "SP-12",
        title: "Ship dashboard MVP",
        dueDate: "2025-11-27T10:00:00.000Z",
        assigneeName: "Hitesh",
        status: "in_progress",
        priority: "High",
      },
      {
        id: "t-2",
        key: "SP-19",
        title: "Investor email sequence",
        dueDate: "2025-11-28T13:00:00.000Z",
        assigneeName: "AI Co-pilot",
        status: "todo",
        priority: "Medium",
      },
    ],
    myTasks: [
      {
        id: "t-1",
        key: "SP-12",
        title: "Ship dashboard MVP",
        status: "in_progress",
        priority: "High",
        dueDate: "2025-11-27T10:00:00.000Z",
      },
      {
        id: "t-4",
        key: "SP-25",
        title: "Refine Sprint radar metrics",
        status: "todo",
        priority: "Medium",
        dueDate: null,
      },
    ],
    recentActivity: [
      {
        id: "a-1",
        type: "task_created",
        taskKey: "SP-25",
        taskTitle: "Refine Sprint radar metrics",
        actorName: "Hitesh",
        createdAt: "2025-11-25T09:00:00.000Z",
        meta: { status: "todo" },
      },
      {
        id: "a-2",
        type: "comment_added",
        taskKey: "SP-12",
        taskTitle: "Ship dashboard MVP",
        actorName: "AI Co-pilot",
        createdAt: "2025-11-25T08:00:00.000Z",
        meta: { snippet: "This chart will be SprintPlanner's signature visual." },
      },
    ],
  },
};

