export type TaskStatus = "backlog" | "todo" | "in_progress" | "done";

export type Priority = "Low" | "Medium" | "High";

export interface BoardTask {
  id: string;
  key: string; // e.g. SP-12
  title: string;
  description?: string;
  status: TaskStatus;
  priority: Priority;
  assigneeName?: string;
  dueDate?: string | null;
  parentTaskId?: string | null;
}

export interface BoardData {
  project: {
    id: string;
    key: string;
    name: string;
  };
  tasks: BoardTask[];
}

export const boardMock: BoardData = {
  project: {
    id: "project-brix-1",
    key: "BX",
    name: "Brix MVP Build",
  },
  tasks: [
    // Week 1
    {
      id: "bx-1",
      key: "BX-1",
      title: "Define Standardized Home Construction Plan Templates",
      description:
        "Research and document 5 standardized home construction templates.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-1-1",
      key: "BX-2",
      title: "Collect competitor template data",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-1",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-1-2",
      key: "BX-3",
      title: "Normalize template structure",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-1",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-1-3",
      key: "BX-4",
      title: "Document 5 templates in Notion",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-1",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-2",
      key: "BX-5",
      title: "Create MVP System Architecture Blueprint",
      description:
        "Design complete architecture for frontend, backend, database, AI layer, and financing workflow.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-2-1",
      key: "BX-6",
      title: "Draft architecture diagram",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-2",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-2-2",
      key: "BX-7",
      title: "List APIs & service layers",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-2",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-3",
      key: "BX-8",
      title: "Draft AI Planning Workflow",
      description:
        "Create user flow + prompt draft + sample output for AI planning.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-3-1",
      key: "BX-9",
      title: "Define user input fields",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-3",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-3-2",
      key: "BX-10",
      title: "Write initial AI prompt",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-3",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-3-3",
      key: "BX-11",
      title: "Create sample output JSON",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-3",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-4",
      key: "BX-12",
      title: "Create Landing Page Wireframe",
      description:
        "Design homepage wireframes with CTA, hero section, and value props.",
      status: "todo",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-4-1",
      key: "BX-13",
      title: "Design hero section",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-4",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-4-2",
      key: "BX-14",
      title: "Design trust + warranty section",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-4",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-4-3",
      key: "BX-15",
      title: "Design CTA + form",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-4",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-5",
      key: "BX-16",
      title: "Define Financing Eligibility Rules",
      description: "Create BNPL eligibility framework + output schema.",
      status: "todo",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-5-1",
      key: "BX-17",
      title: "Define financing input fields",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-5",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-5-2",
      key: "BX-18",
      title: "Set eligibility logic",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-5",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-5-3",
      key: "BX-19",
      title: "Create JSON schema output",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-5",
      assigneeName: "Hitesh",
    },

    // Week 2
    {
      id: "bx-6",
      key: "BX-20",
      title: "Implement Backend Skeleton",
      description: "Create project setup + DB connection + first 3 REST APIs.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-6-1",
      key: "BX-21",
      title: "Initialize project",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-6",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-6-2",
      key: "BX-22",
      title: "Setup PostgreSQL schema",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-6",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-6-3",
      key: "BX-23",
      title: "Create /plans, /cost-estimator, /financing-check APIs",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-6",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-7",
      key: "BX-24",
      title: "Build AI Planning API Integration",
      description: "Integrate OpenAI for template-based planning output.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-7-1",
      key: "BX-25",
      title: "Setup AI client",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-7",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-7-2",
      key: "BX-26",
      title: "Integrate template data",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-7",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-7-3",
      key: "BX-27",
      title: "Return structured JSON output",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-7",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-8",
      key: "BX-28",
      title: "Design Real-Time Monitoring Dashboard Mockup",
      description: "Create UI mockups for progress tracker and CCTV view.",
      status: "todo",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-8-1",
      key: "BX-29",
      title: "Progress tracker UI",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-8",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-8-2",
      key: "BX-30",
      title: "Milestone cards UI",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-8",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-8-3",
      key: "BX-31",
      title: "Mock CCTV UI",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-8",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-9",
      key: "BX-32",
      title: "Build Landing Page Frontend",
      status: "todo",
      description: "Convert wireframes to responsive Next.js static page.",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-9-1",
      key: "BX-33",
      title: "Implement hero section",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-9",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-9-2",
      key: "BX-34",
      title: "Implement warranty section",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-9",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-9-3",
      key: "BX-35",
      title: "Lead capture form",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-9",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-10",
      key: "BX-36",
      title: "Create Materials & Cost Estimator Data Model",
      description:
        "Create ERD and SQL schema for material types and rate cards.",
      status: "todo",
      priority: "Low",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-10-1",
      key: "BX-37",
      title: "Identify material categories",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-10",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-10-2",
      key: "BX-38",
      title: "Define DB schema",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-10",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-10-3",
      key: "BX-39",
      title: "Create SQL migration",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-10",
      assigneeName: "Hitesh",
    },

    // Week 3
    {
      id: "bx-11",
      key: "BX-40",
      title: "Develop Cost Estimator Engine",
      description: "Build material + labor cost calculator (MVP).",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-11-1",
      key: "BX-41",
      title: "Material lookup",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-11",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-11-2",
      key: "BX-42",
      title: "Add labor multipliers",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-11",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-11-3",
      key: "BX-43",
      title: "Final cost calculator",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-11",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-12",
      key: "BX-44",
      title: "Build Financing Eligibility Engine",
      description: "Build scoring model + eligibility logic.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-12-1",
      key: "BX-45",
      title: "Implement rule engine",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-12",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-12-2",
      key: "BX-46",
      title: "Add scoring model",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-12",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-12-3",
      key: "BX-47",
      title: "Return formatted output",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-12",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-13",
      key: "BX-48",
      title: "Develop User Flow (UI Integration)",
      description: "3-screen flow without backend persistence.",
      status: "todo",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-13-1",
      key: "BX-49",
      title: "Plan selection page",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-13",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-13-2",
      key: "BX-50",
      title: "Details input page",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-13",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-13-3",
      key: "BX-51",
      title: "AI result + financing screen",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-13",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-14",
      key: "BX-52",
      title: "Vendor/Partner Onboarding Blueprint",
      description: "2-page document with vendor KYC + verification.",
      status: "todo",
      priority: "Low",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-14-1",
      key: "BX-53",
      title: "Define vendor KYC",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-14",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-14-2",
      key: "BX-54",
      title: "Define onboarding stages",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-14",
      assigneeName: "Hitesh",
    },

    // Week 4
    {
      id: "bx-15",
      key: "BX-55",
      title: "Build Real-Time Monitoring Mock Service",
      description: "Simulate milestone updates for dashboard.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-15-1",
      key: "BX-56",
      title: "Create mock data generator",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-15",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-15-2",
      key: "BX-57",
      title: "Create dashboard API",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-15",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-16",
      key: "BX-58",
      title: "Implement Lead Capture + Admin Review Panel",
      status: "todo",
      description: "Store leads in DB + basic admin view.",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-16-1",
      key: "BX-59",
      title: "Create lead POST endpoint",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-16",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-16-2",
      key: "BX-60",
      title: "Create admin UI table",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-16",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-16-3",
      key: "BX-61",
      title: "Add filtering to admin UI",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-16",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-17",
      key: "BX-62",
      title: "Prepare Pitch Deck + Landing Page Copy",
      description: "10-slide deck + storytelling-based landing page copy.",
      status: "todo",
      priority: "Medium",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-17-1",
      key: "BX-63",
      title: "Problem–solution slide",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-17",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-17-2",
      key: "BX-64",
      title: "Financing model slide",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-17",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-17-3",
      key: "BX-65",
      title: "Write CTA copy",
      status: "todo",
      priority: "Medium",
      parentTaskId: "bx-17",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-18",
      key: "BX-66",
      title: "SEO Foundation Setup",
      description: "Keyword research + 3 blog outlines + metadata.",
      status: "todo",
      priority: "Low",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-18-1",
      key: "BX-67",
      title: "Find competitor keywords",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-18",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-18-2",
      key: "BX-68",
      title: "Write 3 blog outlines",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-18",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-18-3",
      key: "BX-69",
      title: "Add meta title + description",
      status: "todo",
      priority: "Low",
      parentTaskId: "bx-18",
      assigneeName: "Hitesh",
    },

    {
      id: "bx-19",
      key: "BX-70",
      title: "MVP Final Validation & Buffer",
      description: "Fix bugs + polish UI + document tests.",
      status: "todo",
      priority: "High",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-19-1",
      key: "BX-71",
      title: "Run 3 E2E tests",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-19",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-19-2",
      key: "BX-72",
      title: "Fix final issues",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-19",
      assigneeName: "Hitesh",
    },
    {
      id: "bx-19-3",
      key: "BX-73",
      title: "Record demo walkthrough",
      status: "todo",
      priority: "High",
      parentTaskId: "bx-19",
      assigneeName: "Hitesh",
    },
  ],
};
